/**
 * VS Code API subset used by ASN.1 language features.
 *
 * Feature modules import this instead of the `vscode` module.
 *
 * @module
 */
export {
    CancellationTokenNone,
    CodeAction,
    CodeActionKind,
    CompletionItem,
    CompletionItemKind,
    CompletionList,
    CompletionTriggerKind,
    Diagnostic,
    DiagnosticCollection,
    DiagnosticRelatedInformation,
    DiagnosticSeverity,
    DiagnosticTag,
    DocumentHighlight,
    DocumentHighlightKind,
    DocumentSymbol,
    EndOfLine,
    FoldingRange,
    Hover,
    Location,
    MarkdownString,
    ParameterInformation,
    Position,
    Range,
    SelectionRange,
    SignatureHelp,
    SignatureInformation,
    SnippetString,
    SymbolInformation,
    SymbolKind,
    TextDocument,
    TextEdit,
    Uri,
    WorkspaceEdit,
} from "./types_vscode.ts";

export type {
    CancellationToken,
    CodeActionContext,
    CompletionContext,
    Definition,
    DefinitionLink,
    FoldingContext,
    FormattingOptions,
    ProviderResult,
    ReferenceContext,
    Selection,
    TextLine,
    Thenable,
    CodeActionProvider,
    CompletionItemProvider,
    DefinitionProvider,
    DocumentFormattingEditProvider,
    DocumentHighlightProvider,
    DocumentSymbolProvider,
    FoldingRangeProvider,
    HoverProvider,
    ReferenceProvider,
    RenameProvider,
    SelectionRangeProvider,
    SignatureHelpProvider,
    TypeDefinitionProvider,
    WorkspaceSymbolProvider,
} from "./types_vscode.ts";

export {
    deleteTextDocument,
    getAsn1Config,
    getOpenTextDocument,
    getOpenTextDocuments,
    getWorkspaceFolders,
    languages,
    onAsn1ConfigChange,
    resetWorkspaceState,
    setAsn1Config,
    setTextDocument,
    setWorkspaceFolders,
    window,
    workspace,
} from "./workspace.ts";
